### Register a new user
POST {{base_url}}/register
Content-Type: application/json

{
  "firstName": "first",
  "lastName": "last",
  "email": "test@test.com",
  "password": "123Test"
}

### Log in as a user
POST {{base_url}}/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "123Test"
}

### Delete a user
DELETE {{base_url}}/user/{insert_uuid}